/**
 * <Sim Title>
 *
 * Generated by the /new-container or /new-sim-in-container skill.
 * Author fills in the slots. Do NOT bypass the prediction gate or sim-runtime.
 */

import { SimRuntime, type PMOETState } from "@paideia/sim-runtime";
import { PredictionGate } from "@paideia/prediction-gate";
import { FunctionPlot } from "@paideia/plotting"; // example renderer — replace per spec
import spec from "./simulation.yaml";

export default function ForcesAndEquilibrium() {
  return (
    <SimRuntime spec={spec} renderStage={(stage, state) => {
      switch (stage) {
        case "predict":
          return <PredictionGate spec={spec.predict ?? null} />;

        case "manipulate":
          // Wire controls from spec.manipulate.controls to kernel state.
          // Author fills this in. Use core/ui-sim primitives for controls.
          return <div>{/* TODO: manipulate slot */}</div>;

        case "observe":
          // Render via spec.observe.renderers. Renderers are pure of state.
          return <FunctionPlot state={state} />;

        case "explain":
          // Render the Socratic prompt; capture the student's response.
          return <div>{spec.explain.prompt}</div>;

        case "transfer":
          // Transfer problems live in the parent container's problem-solving/ folder.
          // This stage links out to them. Do NOT inline a transfer problem here.
          return null;
      }
    }} />
  );
}
