graph TD
  electricField["Electric field"] --> electricFlux["Electric flux"]
  electricFlux --> gaussianSurface["Gaussian surface"]
  enclosedCharge["Enclosed charge"] --> gaussLaw["E A_G = Q_enc / epsilon0"]
  gaussianSurface --> symmetryArea["Effective area"]
  symmetryArea --> gaussLaw
  gaussLaw --> capacitors["Capacitors and conductors"]
